VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos7"
  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  #config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.provision "shell", :path => "provision/bootstrap.sh"
  #config.vm.synced_folder "../.", "/vagrant", type: "rsync"
  config.vm.synced_folder "../.", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
      vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
   end
end
